# -*- coding: utf-8 -*-
"""Aliasing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14y51k_EKjC4AKjq_PygCa6k6UIhHiP2I
"""

from  googlecolab.import files
file= files.upload()
import pandas as pd
import numpy as np
from datetime import datetime
import sqlite3
database="database.sqlite"
conn=sqllite3.connect(database)
tables= pd.read_sql("""SELECT *
FROM sqlite_master
WHERE type='table';""", conn)
print(tables)

match_details= pd.read_sql("""SELECT Season_Id , Match_Id , v.venue_name ,c.cityname,
                               t.teamname as winner FROM Match
                               inner join venu as v on match.venu_id== v.venu_id
                               inner join city as c on  v.city_id==c.city_id
                               inner join team as t on mtach.match_winner==t.team_id;""", conn)
print(match_details.shape)

