# -*- coding: utf-8 -*-
"""CreateTable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ia6bb_YdEhqS7K1oXgogr8rcdyw2YLQ
"""

from google.colab import files
file= files.upload ()
import sqlite3
connect= sqlite3.connect("database.sqlite")
print("opned data basesuccessfully")
connect.execute("""
                  create table class_10
                  sno int primary key not null,
                  roll_number int not null,
                  name text not null,
                  age int default(16),
                  gender text not null,
                  email_id text notnull,
                  contact_no real not null
                  );""")
print("table created sucessfully")

connect.execute("insert into class_10  (sno,roll_number,name,age,gender,email_id,contact_no) values (1,1,ali,12,male,ali@gmail.com,1234567")
connect.execute("insert into class_10  (sno,roll_number,name,age,gender,email_id,contact_no) values (2,2,ali,13,male,ali@gmail.com,1234567")
connect.execute("insert into class_10  (sno,roll_number,name,age,gender,email_id,contact_no) values (3,3,ali,14,male,ali@gmail.com,1234567")
connect.commit()
print("data inserted sucessfully")

import pandas as pd
tables=pd.read_sql("""select * from sqllite_master where type='table';""",connect )
tables
class10=pd.read_sql("""select * from class10;""",connect )
class10.head()