# -*- coding: utf-8 -*-
"""join.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKCyPS9sVU4c3bnAY3DbIPfYk-vSRRaI
"""

from google.colab import files
file=files.upload()
import pandas as pd
import numpy as np
import sqlite3
database="database.sqlite"
conn=sqlite3.connect(database)
print("opened data sucessfully")
df= pd.read_sql("select * from sql_master where type ='table' ;",conn)
print(df)

joined_city= pd.read_sql("""select c.countryid,c.countryname,ci.cityname,from country c inner join city ci
on c.countryid == ci.countryid ;""",conn)
joined_city.head()

joined_left= pd.read_sql("""select * from player left join season on player.playerid == season.man_of_the_series ;""",conn)
joined_left.head()

join_cross= pd.read_sql("""select c.countryid, c.countryname,ci.cityname from  country c  cross join city ci;""",conn)
join_cross.head()
#

union = pd.read_sql("""select * from player union select * from season;""",conn)
union.head()