# -*- coding: utf-8 -*-
"""lets analyze table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fF4VMXNWGJY6_TjyG6dSqjd5QC-ZWkRb
"""

from google.colab import fiels
file=files.upload()

import sqlite3
database="databse.sqlite"
conn=sqlite.connect(database)
print("opened data base sucessfully ")

import pandas as pd
tables= pd.read_sql("""select * from sqllite_master where type='table';""",conn)
tables

matches = pd.read_sql("""select * from Match;""",conn)
matches