# -*- coding: utf-8 -*-
"""paly with tables part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BGu1C-0dZZJbp8FTUhrHukMLEX1ydWY
"""

from google.colab import files
file=files.upload()

import sqlite3
database="database.sqlite"
conn=sqlite3.connect(database)
print("opened data sucessfully")

import pandas as pd
tables=pd.read_sql("""SELECT name FROM sqlite_master WHERE type='table';""",conn)
tables

matches= pd.read_sql("""SELECT * FROM Match;""",conn)
matches.head()

result1=pd.read_sql("""SELECT AVG(Win_Margin),Match_Winner  FROM Match  where Season_Id==9 Group BY
Match_Winner
ORDER BY AVG(Win_Margin) ;""",conn)
result1

result2=pd.read_sql("""SELECT COUNT(DISTINCT Venue_Id) FROM Match  where Season_Id==9 ; """,conn)
result2

result3=pd.read_sql("""SELECT MIN(Win_Margin),MAX(Win_Margin),AVG(Win_Margin),COUNT(DISTINCT Man_of_the_Match) FROM Match ;""",conn)
result3

result4= pd.read_sql("""SELECT SUM(Win_Margin) FROM Match where Season_Id==9 ;""",conn)
result4