# -*- coding: utf-8 -*-
"""play wirth table .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaczaFvz-TpbcqwQOT-jUOAU41Wkal-C
"""

from google.colab import files
file=files.upload()

import sqlite3
database="database.sqlite"
conn=sqlite3.connect(database)
print("opened data sucessfully")

import pandas as pd
tables=pd.read_sql("""SELECT name FROM sqlite_master WHERE type='table';""",conn)
tables

teams=pd.read_sql("""SELECT * FROM Teams;""",conn)
teams

matches=pd.read_sql("""SELECT * FROM Matches;""",conn)
matches

mi_teams=matches[(matches['team1']=='Mumbai Indians')|(matches['team2']=='Mumbai Indians')]
mi_teams

MI_wins=pd.read_sql("""SELECT * FROM Matches WHERE Match_Winner==7;""",conn)
MI_wins

MI_S8_S9=pd.read_sql("""SELECT * FROM Matches WHERE Match_Winner==7 and Season_Id IN(8,9);""",conn)
MI_S8_S9
#

new_teams= pd.read_sql("""SELECT * FROM Teams WHERE Team_Name LIKE 'De%' ;""",conn)
new_teams

min_max_margin= pd.read_sql("""SELECT MIN(Win_Margin) , MAX(Win_Margin) FROM Match ;""",conn)
min_max_margin

